vendor/xxHash/CMakeLists.txt
When compiling for a non-x86 platform, the x86-dispatch should not be included by explicitly checking the value of the `OS_PLATFORM` query-result.
=> build: Fix xxhash x86 dispatch

libs/ymir-core/src/ymir/hw/vdp/vdp.cpp
This `break;` should be outside of the `if`-statement, otherwise `VDP2DrawLine` will be called in the case that the threaded VDP renderer is enabled.
=> fix(vdp): Ensure `VDP1BeginFrame`-handler breaks out of case-switch

libs/ymir-core/src/ymir/hw/smpc/rtc.cpp
`RTC::m_offset` is uninitialized, which causes functions like `util::datetime::host` to be given undefined-data and further-creates undefined `DateTime`-values which causes even later functions like `SystemStateWindow::DrawRealTimeClock` to crash at times like when opening `System > System State` without an IPL loaded.
=> fix(rtc): Initialize `RTC::m_offset` to zero

CMakeLists.txt, cmake/DetectArchitecture.cmake, vendor/xxHash/CMakeLists.txt
Rather than using the architecture of the host machine, use the architecture that the compiler is designated for by detecting architecture-specific symbols.
Currently, multi-arch build support for MacOS(Universal-Binary with both arm64+x64 in the same binary) does not work due to the mechanism that xxhash uses. Will work on that later.
This allows an `x64` host to make an `arm64` build and the other way around(Tested on Windows and MacOS).
=> build: Implement cross-compilation support

.gitmodules
I changed git modules addresses because I couldn't build on the project on a machine which has no ssh key related to any github account. Modules could not be fetched through SSH channel, so I changed their adresse to be able to fetch them through a HTTPS channel.
This should also fix the [aur](https://aur.archlinux.org/packages/ymir-emu]) package for those who don't have any github account.
Please feel free to reviow and merge if you think it is relevant and like it.
=> Changed: Git modules adresse to HTTPS

libs/ymir-core/include/ymir/util/bit_ops.hpp
Byte-swapping is done at almost every read/write and could be using compiler intrinsics that map directly to optimal assembly rather than emitting explicit debug-code all the time. Should help make debug-build performance a little bit faster.
This allows for more optimal byte-swapping code to be emitted in debug-mode rather than the more explicit debug-mode assembly. This is only implemented for Clang/GCC since MSVC does not have a `constexpr` implementation of their bswap builtins. `std::is_constant_evaluated` is also an actual function-call on MSVC in debug mode, which defeats the purpose of trying to remove additional overhead from endian-swapping.
Before:
After:
=> fix(bit_ops): Use optimized byte_swap specializations on Clang/GCC

libs/ymir-core/include/ymir/util/bit_ops.hpp
Similar to https://github.com/StrikerX3/Ymir/pull/113.
These aren't high-traffic functions at all but added for completeness.
MSVC does have intrinsics like `__rbitl` and `__rbitl` within `arm64intr.h` but they are _not_ usable from a `constexpr` function.
=> fix(bit_ops): Use optimized `bit::reverse` specialization for Clang/GCC

libs/ymir-core/include/ymir/util/bit_ops.hpp
A very small fix I ran into while experimenting with some stuff.
The `~0` terms here is implicitly a 32-bit integer value(`0xFFFFFFFF`), causing cases where bits in the mask larger than 32-bits to fail such as `extract<16,63>`.
The zero just needs to be casted to `UT` to properly handle 64-bit values.
=> fix(bit_ops): Fix `extract/deposit` bit-mask generation

libs/ymir-core/include/ymir/util/data_ops.hpp
These calls to `memcpy` are _actual_ calls to `memcpy` in debug-mode and can be replaced with simpler pointer-arithmetic to remove the overhead of these high-traffic data-ops.
What used to be a `memcpy`-call is now just a simple move-instruction.
`ldrh`/`strh` in the case of the arm64 device I am testing this on. Likely `mov` on x64 and maybe this even lends itself a bit better for the compiler to emit a [movbe](https://www.felixcloutier.com/x86/movbe) instruction.
=> feat(data_ops): Remove `{Read,Write}{BE,LE}` explicit call to `memcpy`

apps/ymir-sdl3/src/app/ui/views/debug/scu_dsp_disassembly_view.cpp, libs/ymir-core/CMakeLists.txt, libs/ymir-core/include/ymir/hw/scu/scu_dsp.hpp, libs/ymir-core/include/ymir/hw/scu/scu_dsp_instr.hpp, libs/ymir-core/src/ymir/hw/scu/scu.cpp, libs/ymir-core/src/ymir/hw/scu/scu_dsp.cpp, tests/ymir-core-tests/src/hw/scu/scu_dsp_tests.cpp
Using a bit-field type rather than `bit_extract` emits more optimal assembly in the general-case for both debug/release cases and simplifies code required to decode and implement instructions. This follows a similar pattern as the `scsp_dsp_instr.hpp` header.
In this case(arm64), rather than calls to `bit_extract`, instructions like `ubfx`, `sbfx`, `and`, and `tbz` are used to directly extract bits for a good little chunk of perf gains here.
=> feat(SCU): Implement Instruction bit-field type

apps/ymir-sdl3/src/app/app.cpp, apps/ymir-sdl3/src/app/profile.cpp
Updates `CheckFolders()` and `CreateFolders()` to take set override paths into account. Moves the `CheckFolders()` and `CreateFolders()` calls to after the config loads.
Resolves #119
=> fix: Take override paths into account when checking and creating folders

libs/ymir-core/include/ymir/hw/vdp/vdp_defs.hpp, libs/ymir-core/src/ymir/hw/vdp/vdp.cpp
Ensuring that `Coord<T>` is a trivial-type allows compilers to make some better assumptions when passing this structure around within registers and faster initialization and other cases where better assembly can be emitted.
I caught a couple places where initialization is faster in debug mode(no function call) and the stack size and traffic is also reduced pretty significantly.
Before:
After:
A next step would possibly be to accelerate Coord/Quad/Line-arithmetic with SIMD unless a third-party SIMD library for linear-algebra ends up being a better candidate for this stuff.
=> feat(vdp): Ensure `Coord<T>` is a trivial-type

apps/ymir-sdl3/res/io.github.strikerx3.ymir.xml
Added metainfo file in preparation for creating a Flatpak
Related PR: https://github.com/StrikerX3/Ymir/pull/188
Some notes:
- Flathub prefers this file to be upstreamed, see https://docs.flathub.org/docs/for-app-authors/requirements#required-metadata
- Used https://freedesktop.org/software/appstream/docs/chap-Metadata.html as a reference
- Used appstreamcli to validate the file
- Same deal with the desktop file, if there's a preferred location, happy to move it!
=> packaging: Add Metainfo File

apps/ymir-sdl3/res/io.github.strikerx3.ymir.desktop
* Added desktop file in preparation for creating a Flatpak
A few notes:
- Currently missing an icon line, I didn't see any icons or logos in the repo. Is this planned at a later date?
- The naming here is a little odd but it follows the D-Bus specification (which Flathub uses and recommends) and the freedesktop specification. See https://dbus.freedesktop.org/doc/dbus-specification.html#message-protocol-names and https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#sect-Metadata-GenericComponent. 
- Instead of using com.github, it uses io.github in accordance to the Flathub docs, https://docs.flatpak.org/en/latest/conventions.html
- "While a project may be hosted on GitHub or GitLab, it does not have control over the github.com or gitlab.com domains. Instead, you should …
=> packaging: Add Desktop File

libs/ymir-core/src/ymir/hw/vdp/vdp.cpp
Implement `Color888AverageMasked` with a64/x64 SIMD specializations.
This generally emits better assembly than the two-at-a-time SIMD that clang emits by default in a lot of cases.
x64 has `_mm_avg_epu8` but this does `(a + b + 1) >> 1` not `(a + b) >> 1` so the 8-bit elements have to be expanded to 16-bit elements for the intermediate sum and shift step before reducing back down to 8-bits. There is no 8-bit element-shift without using [gf2p8affineqb](https://wunkolo.github.io/post/2020/11/gf2p8affineqb-int8-shifting/).
This is totally untested at the moment as I am not sure of any games to test with that consistently use this particular path of layer-blending.
=> feat(VDP): Implement SIMD optimized  `Color888AverageMasked`

apps/ymir-sdl3/src/app/app.cpp, apps/ymir-sdl3/src/app/app.hpp
Adds conversions from Logical window coordinates into "Real" pixel coordinates for Retina displays where relevant.
This fixes MacOS reporting a DPI of `1.0` despite window coordinates mapping to multiple pixels and applies the ImGui scaling mitigation found [here](https://github.com/ocornut/imgui/issues/7779).
Also acquires content scaling based on the _window_ rather than just the primary display. This allows the application to be more responsive to possible Multi-DPI setups or Per-Window DPI settings rather than using the Display Scaling of the primary display.
Before:
After:
Fixes https://github.com/StrikerX3/Ymir/issues/221
=> fix(app): Fix MacOS Retina Display support

.github/workflows/build.yaml, .github/workflows/ci.yaml, CMakeLists.txt, cmake/DefineWrapFile.cmake, cmake/TargetConditionalSources.cmake, vendor/xxHash/CMakeLists.txt
Currently on MacOS, we have to create separate independent builds for each architecture(arm64/x64).
To have a fat-binary(universal binary) the same source files must be able to vary depending on the architecture. So x64-specific files must still be able to be compiled during an ARM64 build, and use a preprocessor mechanism of some sort to disable functionality.
Uses a pattern inspired by Dynarmic, CMake is able to create an intermediate file and add include-guards around specific files, causing them to resolve into empty files depending on the architecture.
Currently the only bit of code that was holding back having singular fat-binary builds is xxHash's x86-specific source files. The new `target_conditional_sources` is used to add x64-specific guards around these files without having to …
=> Implement multi-architecture builds

apps/ymir-sdl3/src/app/app.cpp
ISO 8601 is a standard timestamp-format that has a millisecond resolution variant as well. https://en.wikipedia.org/wiki/ISO_8601
The `Z` specifier is not used since this is strictly local time and not UTC.
=> feat(app): Use ISO 8601 screenshot file names

apps/ymir-sdl3/src/util/os_exception_handler.cpp
Fixes the compilation-errors I was getting when building for Windows on Arm.
The exception-context struct refers to a64  register names a bit differently. I also went ahead and had it print out all the registers.
=> fix(os): Use correct Windows-Arm64 register names

.github/workflows/ci.yaml, COMPILING.md
Added FreeBSD x64 to CI and updated COMPILING to be more consistent with the CI.
Arm64 throws the following errors:
```
In file included from /home/runner/work/Ymir/Ymir/apps/ymir-sdl3/src/app/stb_implementations.cpp:4:
/home/runner/work/Ymir/Ymir/vendor/stb/stb/stb_image_write.h:354:59: error: non-const lvalue reference to type '__builtin_va_list' cannot bind to a value of unrelated type 'va_list' (aka 'std::__va_list')
354 |          case '1': { unsigned char x = STBIW_UCHAR(va_arg(v, int));
|                                                           ^
/usr/local/llvm19/lib/clang/19/include/__stdarg_va_arg.h:20:43: note: expanded from macro 'va_arg'
20 | #define va_arg(ap, type) __builtin_va_arg(ap, type)
|                                           ^~ …
```
=> FreeBSD CI

apps/ymir-sdl3/src/app/app.cpp, apps/ymir-sdl3/src/app/cmdline_opts.hpp, apps/ymir-sdl3/src/app/settings.cpp, apps/ymir-sdl3/src/app/settings.hpp, apps/ymir-sdl3/src/main.cpp
Ymir tries to detect the profile path by locating Ymir.toml in the portable path first and then in the user's home directory. If it can't locate Ymir.toml in one of these directories, it will show a dialog on startup, in which the desired profile mode can be selected. "Installed" mode uses the user's home directory and "Portable" mode uses the portable path, i.e. the current working directory.
Specifying the -p option still overrides this behavior and uses the given custom profile path.
A new option -u is available which forces usage of the user's home directory and which overrides all other behavior.
Contains additional cosmetic code changes:
* put the profile selection code closer to where the settings file is loaded
* replace multiple occurrences of string literal "Ymir.toml" with a …
=> feat(app): Automatically detect profile path and allow using the user profile path from the OS

apps/ymir-sdl3/src/util/std_lib.cpp
This adds the _M_ARM64 check to address build failure when using MSYS2 environment on Windows ARM64
=> fix (build): Use localtime_s on Windows ARM64

.github/workflows/build.yaml, .github/workflows/ci.yaml
This PR adds in Windows ARM64 builds using windows-11-arm runner.
The changes were tested on a separate branch here: https://github.com/tordona/Ymir/tree/refs/heads/ci-test-stub
The output binaries, and locally built binaries were tested on physical hardware listed below
**Test Devices**
| Device | CPU |
| -------- | ------- |
| Microsoft Surface Pro X  | Microsoft SQ2 |
| Dell Inspiron 3420 | Snapdragon 8cx Gen 2 |
| Lenovo ThinkPad x13s | Snapdragon 8cx Gen 3 |
| Lenovo IdeaPad 5x | Snapdragon X Plus X1P-42-100 |
=> build: add win arm64 ci support

libs/ymir-core/include/ymir/util/lsn_denormals.hpp
The project compiles just fine on cl-clang but gets a compilation error on MSVC due to the usage of inline assembly. MSVC does not support inline assembly(`__asm__`), but the `_{Read,Write}StatusReg` intrinsics provided by MSVC map directly to `{mrs,msr}` instructions, allowing for direct `FPCR` access using register `ARM64_SYSREG(0b11, 0b011, 0b0100, 0b100, 0b000)`. This matches output of builtins like `__builtin_aarch64_{get,set}_fpcr` provided by other compilers(`mrs x0, FPCR`/`msr FPCR, x0`)
=> fix: use `{mrs,msr}` intrinsics for arm64 MSVC

.github/workflows/ci.yaml
llvm21 is now available in the quarterly package repository, so the CI can revert to using the more stable quarterly branch instead of the rolling-release latest branch.
=> build: Revert to quarterly branch in FreeBSD CI
